language: php
dist: trusty
sudo: false

php:
  - '7.2'
  - '7.3'
  - '7.4'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y fswatch
  - printf "\n" | pecl install swoole

install:
  - travis_retry composer install --no-suggest --prefer-dist

script:
  - composer test