language: php
dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - pecl install swoole
  - pecl install inotify

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit